tweaks to get slow queries showing up in monitoring

diff --git a/px-bookkeeper/3-bbq-bookkeeper.yaml b/px-bookkeeper/3-bbq-bookkeeper.yaml
--- a/px-bookkeeper/3-bbq-bookkeeper.yaml
+++ b/px-bookkeeper/3-bbq-bookkeeper.yaml
@@ -25,6 +25,19 @@ spec:
         app: bbqinventoryapp
     spec:
       containers:
+      - name: load-generator
+        image: curlimages/curl:7.85.0
+        command: ["/bin/sh", "-c"]
+        args:
+          - |
+            while true; do
+              curl -s localhost:8080/inventory-by-location?location=Seattle > /dev/null
+              if [ $? -eq 0 ]; then
+                echo "Successfully accessed localhost:8080"
+              else
+                echo "Failed to access localhost:8080"
+              fi
+            done
       - env:
         - name: DB_INIT_USER
           value: sa
@@ -46,10 +59,10 @@ spec:
               name: bbq-bookkeeper-secret
         livenessProbe:
           httpGet:
-            path: /
+            path: /inventory-by-location
             port: 8080
           initialDelaySeconds: 1
-          periodSeconds: 1
+          periodSeconds: 2
         image: eshanks16/bbqbookkeeper:ea26ddd # ea26ddd - old app version, 83af344 - new app version
         imagePullPolicy: Always
         name: bbqinventoryapp
